# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Overview'
  link: '/overview'
- label: Tools
  items:
    - label: 'Polyglot Code Explorer'
      link: /tools/explorer/description
    - label: 'Polyglot Code Scanner'
      link: '/tools/scanner/description'
    - label: 'Polyglot Code Offline Layout'
      link: '/tools/layout/description'
- label: 'How To guides'
  items:
    - label: 'How to run the Explorer'
      link: /tools/explorer/howto
    - label: 'How to run the Scanner'
      link: /tools/scanner/howto
    - label: 'How to run the Layout'
      link: /tools/layout/howto
